
export const StickerIcons = {
    fill:{
        0: 'airplane',
        1: 'basket',
        2: 'documents',
        3: 'bandage',
        4: 'basketball',
        5: 'beer',
        6: 'book',
        7: 'bookmark',
        8: 'briefcase',
        9: 'color-palette',
        10: 'bulb',
        11: 'cash',
        12: 'chatbubbles',
        13: 'checkmark-circle',
        14: 'compass',
        15: 'film',
        16: 'flame',
        17: 'flash',
        18: 'flower',
        19: 'heart',
        20: 'home',
        21: 'location',
        22: 'moon',
        23: 'notifications',
        24: 'paper-plane',
        25: 'paw',
        26: 'pricetags',
        27: 'school',
        28: 'star',
        29: 'ticket',
        30: 'water',
        31: 'leaf',
        32: 'fast-food',
        33: 'construct',
        34: 'camera',
        35: 'cut'
    },
    outline:{
        0: 'airplane-outline',
        1: 'basket-outline',
        2: 'documents-outline',
        3: 'bandage-outline',
        4: 'basketball-outline',
        5: 'beer-outline',
        6: 'book-outline',
        7: 'bookmark-outline',
        8: 'briefcase-outline',
        9: 'color-palette-outline',
        10: 'bulb-outline',
        11: 'cash-outline',
        12: 'chatbubbles-outline',
        13: 'checkmark-circle-outline',
        14: 'compass-outline',
        15: 'film-outline',
        16: 'flame-outline',
        17: 'flash-outline',
        18: 'flower-outline',
        19: 'heart-outline',
        20: 'home-outline',
        21: 'location-outline',
        22: 'moon-outline',
        23: 'notifications-outline',
        24: 'paper-plane-outline',
        25: 'paw-outline',
        26: 'pricetags-outline',
        27: 'school-outline',
        28: 'star-outline',
        29: 'ticket-outline',
        30: 'water-outline',
        31: 'leaf-outline',
        32: 'fast-food-outline',
        33: 'construct-outline',
        34: 'camera-outline',
        35: 'cut-outline'

    },
};